version: "3.9"

services:
  webapp:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    image: booking/user-service
    env_file:
      - .env
    ports:
      - target: $SERVER_PORT
        published: 9000
        protocol: tcp
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
