version: "3.9"

services:
  webapp:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    image: booking/user-service
    env_file:
      - .env
    ports:
      - target: $SERVER_PORT
        published: 9000
        protocol: tcp
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
  keycloak:
    container_name: booking-keycloak
    image: quay.io/keycloak/keycloak:18.0.1
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"